# Generated by Django 5.1.5 on 2026-02-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list, help_text='List of extracted skills')),
                ('missing_skills', models.JSONField(default=list, help_text='Suggested skills to add')),
                ('suggested_roles', models.JSONField(default=list, help_text='Suggested job roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Resume analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
