# Generated by Django 5.1.5 on 2026-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF or TXT; stored in media folder', upload_to='resumes/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list, help_text='Extracted skills')),
                ('missing_skills', models.JSONField(default=list, help_text='Suggested skills to add')),
                ('suggested_roles', models.JSONField(default=list, help_text='Suggested job roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Uploaded resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ResumeAnalysis',
        ),
    ]
