# Generated by Django 5.1.5 on 2026-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_switch_to_uploaded_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedresume',
            name='improvement_tips',
            field=models.JSONField(default=list, help_text='Resume improvement tips from AI'),
        ),
        migrations.AlterField(
            model_name='uploadedresume',
            name='skills',
            field=models.JSONField(default=list, help_text='Detected skills'),
        ),
        migrations.AlterField(
            model_name='uploadedresume',
            name='suggested_roles',
            field=models.JSONField(default=list, help_text='Suitable job roles'),
        ),
    ]
